import type { NutritionValues } from '@/types/nutrition';

export type FoodCategory =
  | 'staple'
  | 'protein'
  | 'vegetable'
  | 'fruit'
  | 'dairy'
  | 'snack'
  | 'condiment';

export type FoodIconKey = 'grain' | 'meat' | 'fish' | 'egg' | 'leaf' | 'fruit' | 'drop' | 'cookie';

export type FoodCatalogItem = {
  id: string;
  name: string;
  category: FoodCategory;
  icon: FoodIconKey;
  portionHint: string;
  defaultWeightG: number;
  nutritionPer100g: NutritionValues;
};

type FoodCategoryMeta = {
  value: FoodCategory;
  label: string;
  hint: string;
};

function food(
  id: string,
  name: string,
  category: FoodCategory,
  icon: FoodIconKey,
  portionHint: string,
  defaultWeightG: number,
  nutritionPer100g: NutritionValues,
): FoodCatalogItem {
  return { id, name, category, icon, portionHint, defaultWeightG, nutritionPer100g };
}

export const FOOD_CATEGORIES: FoodCategoryMeta[] = [
  { value: 'staple', label: '主食', hint: '米面薯类和基础能量' },
  { value: 'protein', label: '蛋白', hint: '肉蛋豆制品和海鲜' },
  { value: 'vegetable', label: '蔬菜', hint: '叶菜菌菇和清爽配菜' },
  { value: 'fruit', label: '水果', hint: '水果和天然糖分来源' },
  { value: 'dairy', label: '乳品', hint: '牛奶酸奶和奶酪' },
  { value: 'snack', label: '加餐', hint: '坚果零食和轻食补充' },
  { value: 'condiment', label: '调味', hint: '酱料汤汁和烹调油脂' },
];

export const FOOD_WEIGHT_OPTIONS = [10, 15, 20, 30, 50, 80, 100, 120, 150, 200, 250, 300] as const;

export const FOOD_CATALOG: FoodCatalogItem[] = [
  food('rice', '米饭', 'staple', 'grain', '一小碗约 150g', 150, {
    calories: 116,
    protein: 2.6,
    fat: 0.3,
    carbs: 25.9,
    fiber: 0.3,
    sodium: 2,
    sugar: 0.1,
  }),
  food('brown-rice', '糙米饭', 'staple', 'grain', '耐饿感更强，适合替换部分白米饭', 150, {
    calories: 111,
    protein: 2.6,
    fat: 0.9,
    carbs: 23,
    fiber: 1.8,
    sodium: 4,
    sugar: 0.4,
  }),
  food('oatmeal', '燕麦粥', 'staple', 'grain', '早餐常见，饱腹感不错', 220, {
    calories: 68,
    protein: 2.4,
    fat: 1.4,
    carbs: 12,
    fiber: 1.7,
    sodium: 49,
    sugar: 0.5,
  }),
  food('whole-wheat-bread', '全麦面包', 'staple', 'grain', '两片约 60g', 60, {
    calories: 247,
    protein: 12.5,
    fat: 4.2,
    carbs: 41.4,
    fiber: 6.8,
    sodium: 423,
    sugar: 5.1,
  }),
  food('sweet-potato', '红薯', 'staple', 'grain', '蒸煮更稳妥，适合作主食替换', 180, {
    calories: 86,
    protein: 1.6,
    fat: 0.1,
    carbs: 20.1,
    fiber: 3,
    sodium: 55,
    sugar: 4.2,
  }),
  food('corn', '玉米', 'staple', 'grain', '一根约 180g', 180, {
    calories: 106,
    protein: 4,
    fat: 1.2,
    carbs: 22.8,
    fiber: 2.9,
    sodium: 15,
    sugar: 4.5,
  }),
  food('noodles', '面条', 'staple', 'grain', '熟面按实际克重估算', 180, {
    calories: 131,
    protein: 4.5,
    fat: 1.6,
    carbs: 24.9,
    fiber: 1.4,
    sodium: 1,
    sugar: 0.6,
  }),
  food('quinoa', '藜麦饭', 'staple', 'grain', '适合想提高饱腹感时搭配', 150, {
    calories: 120,
    protein: 4.4,
    fat: 1.9,
    carbs: 21.3,
    fiber: 2.8,
    sodium: 7,
    sugar: 0.9,
  }),
  food('potato', '土豆', 'staple', 'grain', '做主食时要留意额外用油', 160, {
    calories: 77,
    protein: 2,
    fat: 0.1,
    carbs: 17.6,
    fiber: 2.2,
    sodium: 6,
    sugar: 0.8,
  }),
  food('mantou', '馒头', 'staple', 'grain', '一个中等约 90g', 90, {
    calories: 223,
    protein: 7,
    fat: 1.1,
    carbs: 47,
    fiber: 1.5,
    sodium: 165,
    sugar: 1,
  }),

  food('chicken-breast', '鸡胸肉', 'protein', 'meat', '高蛋白、低脂，适合日常补充', 120, {
    calories: 165,
    protein: 31,
    fat: 3.6,
    carbs: 0,
    fiber: 0,
    sodium: 74,
    sugar: 0,
  }),
  food('beef', '瘦牛肉', 'protein', 'meat', '铁含量较高，热菜常见', 120, {
    calories: 187,
    protein: 20.4,
    fat: 12,
    carbs: 0,
    fiber: 0,
    sodium: 72,
    sugar: 0,
  }),
  food('salmon', '三文鱼', 'protein', 'fish', '富含脂肪酸，适合煎烤或沙拉', 120, {
    calories: 208,
    protein: 20.4,
    fat: 13.4,
    carbs: 0,
    fiber: 0,
    sodium: 59,
    sugar: 0,
  }),
  food('shrimp', '虾仁', 'protein', 'fish', '蛋白密度高，家常配菜常见', 100, {
    calories: 99,
    protein: 23.6,
    fat: 0.3,
    carbs: 0.9,
    fiber: 0,
    sodium: 111,
    sugar: 0,
  }),
  food('egg', '鸡蛋', 'protein', 'egg', '一枚约 50g', 50, {
    calories: 144,
    protein: 13.3,
    fat: 8.8,
    carbs: 2.8,
    fiber: 0,
    sodium: 131,
    sugar: 0.3,
  }),
  food('tofu', '北豆腐', 'protein', 'egg', '植物蛋白补充，适合汤和清炒', 100, {
    calories: 81,
    protein: 8.1,
    fat: 4.2,
    carbs: 1.9,
    fiber: 0.6,
    sodium: 7,
    sugar: 0.5,
  }),
  food('pork-tenderloin', '里脊肉', 'protein', 'meat', '适合清炒或滑炒', 120, {
    calories: 143,
    protein: 20.3,
    fat: 6.2,
    carbs: 0,
    fiber: 0,
    sodium: 57,
    sugar: 0,
  }),
  food('cod', '鳕鱼', 'protein', 'fish', '清蒸和煎制都常见', 120, {
    calories: 82,
    protein: 17.8,
    fat: 0.7,
    carbs: 0,
    fiber: 0,
    sodium: 72,
    sugar: 0,
  }),
  food('tuna', '金枪鱼', 'protein', 'fish', '做沙拉和轻食较常见', 100, {
    calories: 132,
    protein: 28,
    fat: 1.3,
    carbs: 0,
    fiber: 0,
    sodium: 37,
    sugar: 0,
  }),
  food('edamame', '毛豆', 'protein', 'leaf', '加餐和配菜都合适', 90, {
    calories: 131,
    protein: 13,
    fat: 5.7,
    carbs: 10.5,
    fiber: 5.2,
    sodium: 6,
    sugar: 2.2,
  }),

  food('broccoli', '西兰花', 'vegetable', 'leaf', '搭配主菜很常见', 100, {
    calories: 34,
    protein: 2.8,
    fat: 0.4,
    carbs: 6.6,
    fiber: 2.6,
    sodium: 33,
    sugar: 1.7,
  }),
  food('spinach', '菠菜', 'vegetable', 'leaf', '焯水和清炒都常见', 100, {
    calories: 23,
    protein: 2.9,
    fat: 0.4,
    carbs: 3.6,
    fiber: 2.2,
    sodium: 79,
    sugar: 0.4,
  }),
  food('lettuce', '生菜', 'vegetable', 'leaf', '轻食和卷饼常用', 80, {
    calories: 15,
    protein: 1.4,
    fat: 0.2,
    carbs: 2.9,
    fiber: 1.3,
    sodium: 28,
    sugar: 0.8,
  }),
  food('tomato', '西红柿', 'vegetable', 'leaf', '冷热菜都很常见', 100, {
    calories: 18,
    protein: 0.9,
    fat: 0.2,
    carbs: 3.9,
    fiber: 1.2,
    sodium: 5,
    sugar: 2.6,
  }),
  food('cucumber', '黄瓜', 'vegetable', 'leaf', '凉拌和配餐常见', 100, {
    calories: 16,
    protein: 0.7,
    fat: 0.1,
    carbs: 3.6,
    fiber: 0.5,
    sodium: 2,
    sugar: 1.7,
  }),
  food('bok-choy', '上海青', 'vegetable', 'leaf', '清炒和配面常见', 100, {
    calories: 13,
    protein: 1.5,
    fat: 0.2,
    carbs: 2.2,
    fiber: 1,
    sodium: 65,
    sugar: 1.2,
  }),
  food('cabbage', '卷心菜', 'vegetable', 'leaf', '清炒和炖煮都常见', 100, {
    calories: 25,
    protein: 1.3,
    fat: 0.1,
    carbs: 5.8,
    fiber: 2.5,
    sodium: 18,
    sugar: 3.2,
  }),
  food('carrot', '胡萝卜', 'vegetable', 'leaf', '经常作为配菜出现', 80, {
    calories: 41,
    protein: 0.9,
    fat: 0.2,
    carbs: 9.6,
    fiber: 2.8,
    sodium: 69,
    sugar: 4.7,
  }),
  food('cauliflower', '菜花', 'vegetable', 'leaf', '清炒和烤箱做法都合适', 100, {
    calories: 25,
    protein: 1.9,
    fat: 0.3,
    carbs: 5,
    fiber: 2,
    sodium: 30,
    sugar: 1.9,
  }),
  food('shiitake', '香菇', 'vegetable', 'leaf', '适合搭配肉类和汤品', 80, {
    calories: 34,
    protein: 2.2,
    fat: 0.5,
    carbs: 6.8,
    fiber: 2.5,
    sodium: 9,
    sugar: 2.4,
  }),

  food('apple', '苹果', 'fruit', 'fruit', '一个中等约 180g', 180, {
    calories: 52,
    protein: 0.3,
    fat: 0.2,
    carbs: 13.8,
    fiber: 2.4,
    sodium: 1,
    sugar: 10.4,
  }),
  food('banana', '香蕉', 'fruit', 'fruit', '运动前后都常见', 120, {
    calories: 89,
    protein: 1.1,
    fat: 0.3,
    carbs: 22.8,
    fiber: 2.6,
    sodium: 1,
    sugar: 12.2,
  }),
  food('blueberry', '蓝莓', 'fruit', 'fruit', '加酸奶时很常见', 80, {
    calories: 57,
    protein: 0.7,
    fat: 0.3,
    carbs: 14.5,
    fiber: 2.4,
    sodium: 1,
    sugar: 10,
  }),
  food('orange', '橙子', 'fruit', 'fruit', '补充维 C 很方便', 180, {
    calories: 47,
    protein: 0.9,
    fat: 0.1,
    carbs: 11.8,
    fiber: 2.4,
    sodium: 0,
    sugar: 9.4,
  }),
  food('kiwi', '猕猴桃', 'fruit', 'fruit', '酸甜清爽，早餐常见', 100, {
    calories: 61,
    protein: 1.1,
    fat: 0.5,
    carbs: 14.7,
    fiber: 3,
    sodium: 3,
    sugar: 9,
  }),
  food('strawberry', '草莓', 'fruit', 'fruit', '热量更轻，适合加餐', 100, {
    calories: 32,
    protein: 0.7,
    fat: 0.3,
    carbs: 7.7,
    fiber: 2,
    sodium: 1,
    sugar: 4.9,
  }),
  food('pear', '梨', 'fruit', 'fruit', '一个中等约 180g', 180, {
    calories: 57,
    protein: 0.4,
    fat: 0.1,
    carbs: 15.2,
    fiber: 3.1,
    sodium: 1,
    sugar: 9.8,
  }),
  food('grapefruit', '西柚', 'fruit', 'fruit', '早餐或下午都合适', 180, {
    calories: 42,
    protein: 0.8,
    fat: 0.1,
    carbs: 10.7,
    fiber: 1.6,
    sodium: 0,
    sugar: 6.9,
  }),

  food('milk', '低脂牛奶', 'dairy', 'drop', '一杯约 250g', 250, {
    calories: 54,
    protein: 3.4,
    fat: 1.5,
    carbs: 5.1,
    fiber: 0,
    sodium: 44,
    sugar: 5.1,
  }),
  food('skim-milk', '脱脂牛奶', 'dairy', 'drop', '更控脂时可选', 250, {
    calories: 35,
    protein: 3.4,
    fat: 0.1,
    carbs: 5,
    fiber: 0,
    sodium: 50,
    sugar: 5,
  }),
  food('yogurt', '无糖酸奶', 'dairy', 'drop', '早餐和加餐常见', 180, {
    calories: 66,
    protein: 3.5,
    fat: 3.2,
    carbs: 5,
    fiber: 0,
    sodium: 52,
    sugar: 4.7,
  }),
  food('greek-yogurt', '希腊酸奶', 'dairy', 'drop', '蛋白更高，口感更稠', 150, {
    calories: 97,
    protein: 9,
    fat: 4,
    carbs: 3.6,
    fiber: 0,
    sodium: 36,
    sugar: 3.2,
  }),
  food('high-protein-yogurt', '高蛋白酸奶', 'dairy', 'drop', '控饿感更友好', 180, {
    calories: 76,
    protein: 8.5,
    fat: 2,
    carbs: 4.8,
    fiber: 0,
    sodium: 58,
    sugar: 4.5,
  }),
  food('light-cheese', '低脂奶酪', 'dairy', 'drop', '三明治和早餐里常见', 30, {
    calories: 256,
    protein: 23,
    fat: 17,
    carbs: 3.5,
    fiber: 0,
    sodium: 650,
    sugar: 1.5,
  }),

  food('almond', '杏仁', 'snack', 'cookie', '一小把约 25g', 25, {
    calories: 579,
    protein: 21.2,
    fat: 49.9,
    carbs: 21.6,
    fiber: 12.5,
    sodium: 1,
    sugar: 4.4,
  }),
  food('walnut', '核桃', 'snack', 'cookie', '份量更需要控制', 25, {
    calories: 654,
    protein: 15.2,
    fat: 65.2,
    carbs: 13.7,
    fiber: 6.7,
    sodium: 2,
    sugar: 2.6,
  }),
  food('cashew', '腰果', 'snack', 'cookie', '口感较软，适合小份加餐', 25, {
    calories: 553,
    protein: 18.2,
    fat: 43.8,
    carbs: 30.2,
    fiber: 3.3,
    sodium: 12,
    sugar: 5.9,
  }),
  food('pistachio', '开心果', 'snack', 'cookie', '纤维和蛋白都不错', 25, {
    calories: 562,
    protein: 20.3,
    fat: 45.4,
    carbs: 27.2,
    fiber: 10.3,
    sodium: 1,
    sugar: 7.7,
  }),
  food('peanut', '花生', 'snack', 'cookie', '更适合小份量加餐', 25, {
    calories: 567,
    protein: 25.8,
    fat: 49.2,
    carbs: 16.1,
    fiber: 8.5,
    sodium: 18,
    sugar: 4.7,
  }),
  food('dark-chocolate', '黑巧克力', 'snack', 'cookie', '可可含量更高会更稳妥', 20, {
    calories: 598,
    protein: 7.8,
    fat: 42.6,
    carbs: 45.9,
    fiber: 10.9,
    sodium: 20,
    sugar: 24.2,
  }),
  food('granola', '格兰诺拉', 'snack', 'cookie', '早餐和酸奶搭配常见', 40, {
    calories: 471,
    protein: 10,
    fat: 20.1,
    carbs: 64.2,
    fiber: 8.5,
    sodium: 147,
    sugar: 19.8,
  }),
  food('popcorn', '爆米花', 'snack', 'cookie', '无糖无黄油版本更稳妥', 30, {
    calories: 387,
    protein: 12.9,
    fat: 4.5,
    carbs: 77.8,
    fiber: 14.5,
    sodium: 8,
    sugar: 0.9,
  }),

  food('cooking-oil', '食用油', 'condiment', 'drop', '炒菜和煎制时的额外油脂', 10, {
    calories: 899,
    protein: 0,
    fat: 99.9,
    carbs: 0,
    fiber: 0,
    sodium: 0,
    sugar: 0,
  }),
  food('satay-sauce', '沙茶酱', 'condiment', 'drop', '拌炒牛肉、海鲜和火锅蘸料常见', 15, {
    calories: 430,
    protein: 8,
    fat: 35,
    carbs: 18,
    fiber: 1,
    sodium: 1500,
    sugar: 6,
  }),
  food('soy-sauce', '酱油', 'condiment', 'drop', '提鲜调味，用量通常不大', 10, {
    calories: 53,
    protein: 8.1,
    fat: 0.1,
    carbs: 4.9,
    fiber: 0.8,
    sodium: 5700,
    sugar: 0.4,
  }),
  food('chili-oil', '辣椒油', 'condiment', 'drop', '红油和拌汁常见', 10, {
    calories: 895,
    protein: 0.5,
    fat: 99,
    carbs: 0.8,
    fiber: 0.2,
    sodium: 180,
    sugar: 0.1,
  }),
  food('savory-sauce', '咸味酱汁', 'condiment', 'drop', '看得出有酱汁但无法明确种类时使用', 20, {
    calories: 160,
    protein: 2,
    fat: 8,
    carbs: 20,
    fiber: 0.5,
    sodium: 1800,
    sugar: 10,
  }),
  food('thick-gravy', '勾芡酱汁', 'condiment', 'drop', '盘底浓汁、挂芡明显时使用', 20, {
    calories: 120,
    protein: 1,
    fat: 4,
    carbs: 22,
    fiber: 0.2,
    sodium: 1200,
    sugar: 8,
  }),
];
