import type { NutritionValues } from '@/types/nutrition';

export type FoodCategory =
  | 'staple'
  | 'protein'
  | 'vegetable'
  | 'fruit'
  | 'dairy'
  | 'snack'
  | 'condiment';

export type FoodIconKey = 'grain' | 'meat' | 'fish' | 'egg' | 'leaf' | 'fruit' | 'drop' | 'cookie';

type FoodNutritionSource = {
  provider: 'USDA FoodData Central';
  dataType: 'SR Legacy';
  fdcId: number;
  description: string;
};

export type FoodCatalogItem = {
  id: string;
  name: string;
  category: FoodCategory;
  icon: FoodIconKey;
  portionHint: string;
  defaultWeightG: number;
  nutritionPer100g: NutritionValues;
  source: FoodNutritionSource;
};

type FoodCategoryMeta = {
  value: FoodCategory;
  label: string;
  hint: string;
};

function usda(fdcId: number, description: string): FoodNutritionSource {
  return { provider: 'USDA FoodData Central', dataType: 'SR Legacy', fdcId, description };
}

function food(
  id: string,
  name: string,
  category: FoodCategory,
  icon: FoodIconKey,
  portionHint: string,
  defaultWeightG: number,
  nutritionPer100g: NutritionValues,
  source: FoodNutritionSource,
): FoodCatalogItem {
  return { id, name, category, icon, portionHint, defaultWeightG, nutritionPer100g, source };
}

export const FOOD_CATEGORIES: FoodCategoryMeta[] = [
  { value: 'staple', label: '主食', hint: '米面薯类和基础能量' },
  { value: 'protein', label: '蛋白', hint: '肉蛋豆制品和海鲜' },
  { value: 'vegetable', label: '蔬菜', hint: '叶菜菌菇和清爽配菜' },
  { value: 'fruit', label: '水果', hint: '水果和天然糖分来源' },
  { value: 'dairy', label: '乳品', hint: '牛奶酸奶和奶酪' },
  { value: 'snack', label: '加餐', hint: '坚果零食和轻食补充' },
  { value: 'condiment', label: '调味', hint: '酱料汤汁和烹调油脂' },
];

export const FOOD_WEIGHT_OPTIONS = [5, 10, 15, 20, 25, 30, 40, 50, 80, 100, 120, 150, 180, 200, 250, 300] as const;

// 营养值来自 USDA FoodData Central SR Legacy，单位为每 100g；录入克重时由应用按 weight_g / 100 换算。
export const FOOD_CATALOG: FoodCatalogItem[] = [
  food("rice", "米饭", "staple", "grain", "熟白米饭，一小碗约 150g", 150, {
    calories: 130,
    protein: 2.4,
    fat: 0.2,
    carbs: 28.6,
    fiber: 0,
    sodium: 0,
    sugar: 0,
  }, usda(168930, "Rice, white, medium-grain, cooked, unenriched")),
  food("brown-rice", "糙米饭", "staple", "grain", "熟糙米饭，饱腹感更强", 150, {
    calories: 123,
    protein: 2.7,
    fat: 1,
    carbs: 25.6,
    fiber: 1.6,
    sodium: 4,
    sugar: 0.2,
  }, usda(169704, "Rice, brown, long-grain, cooked (Includes foods for USDA's Food Distribution Program)")),
  food("short-grain-rice", "短粒米饭", "staple", "grain", "口感更黏，寿司饭常见", 150, {
    calories: 130,
    protein: 2.4,
    fat: 0.2,
    carbs: 28.7,
    fiber: 0,
    sodium: 0,
    sugar: 0,
  }, usda(168932, "Rice, white, short-grain, cooked, unenriched")),
  food("rice-noodles", "米粉/米线", "staple", "grain", "熟米粉按实际克重估算", 180, {
    calories: 108,
    protein: 1.8,
    fat: 0.2,
    carbs: 24,
    fiber: 1,
    sodium: 19,
    sugar: 0,
  }, usda(168914, "Rice noodles, cooked")),
  food("pasta", "意面", "staple", "grain", "熟意面按实际克重估算", 180, {
    calories: 158,
    protein: 5.8,
    fat: 0.9,
    carbs: 30.9,
    fiber: 1.8,
    sodium: 1,
    sugar: 0.6,
  }, usda(168928, "Pasta, cooked, unenriched, without added salt")),
  food("egg-noodles", "鸡蛋面", "staple", "grain", "熟面按实际克重估算", 180, {
    calories: 138,
    protein: 4.5,
    fat: 2.1,
    carbs: 25.2,
    fiber: 1.2,
    sodium: 165,
    sugar: 0.4,
  }, usda(168919, "Noodles, egg, cooked, enriched, with added salt")),
  food("bulgur", "布格麦饭", "staple", "grain", "熟布格麦，可替换米饭", 150, {
    calories: 83,
    protein: 3.1,
    fat: 0.2,
    carbs: 18.6,
    fiber: 4.5,
    sodium: 5,
    sugar: 0.1,
  }, usda(170287, "Bulgur, cooked")),
  food("barley", "大麦饭", "staple", "grain", "熟大麦，适合杂粮搭配", 150, {
    calories: 123,
    protein: 2.3,
    fat: 0.4,
    carbs: 28.2,
    fiber: 3.8,
    sodium: 3,
    sugar: 0.3,
  }, usda(170285, "Barley, pearled, cooked")),
  food("couscous", "库斯库斯", "staple", "grain", "熟库斯库斯，轻食常见", 150, {
    calories: 112,
    protein: 3.8,
    fat: 0.2,
    carbs: 23.2,
    fiber: 1.4,
    sodium: 5,
    sugar: 0.1,
  }, usda(169700, "Couscous, cooked")),
  food("quinoa", "藜麦饭", "staple", "grain", "熟藜麦，蛋白和纤维更高", 150, {
    calories: 120,
    protein: 4.4,
    fat: 1.9,
    carbs: 21.3,
    fiber: 2.8,
    sodium: 7,
    sugar: 0.9,
  }, usda(168917, "Quinoa, cooked")),
  food("millet", "小米饭", "staple", "grain", "熟小米，早餐或杂粮饭常见", 150, {
    calories: 119,
    protein: 3.5,
    fat: 1,
    carbs: 23.7,
    fiber: 1.3,
    sodium: 2,
    sugar: 0.1,
  }, usda(168871, "Millet, cooked")),
  food("buckwheat", "荞麦饭", "staple", "grain", "熟荞麦，适合做杂粮主食", 150, {
    calories: 92,
    protein: 3.4,
    fat: 0.6,
    carbs: 19.9,
    fiber: 2.7,
    sodium: 4,
    sugar: 0.9,
  }, usda(170686, "Buckwheat groats, roasted, cooked")),
  food("oatmeal", "燕麦粥", "staple", "grain", "即食燕麦加水后的熟重", 220, {
    calories: 68,
    protein: 2.4,
    fat: 1.4,
    carbs: 11.7,
    fiber: 1.7,
    sodium: 49,
    sugar: 0.5,
  }, usda(171662, "Cereals, oats, instant, fortified, plain, prepared with water (boiling water added or microwaved)")),
  food("oats-dry", "燕麦片", "staple", "grain", "干燕麦片，冲泡前称重", 40, {
    calories: 389,
    protein: 16.9,
    fat: 6.9,
    carbs: 66.3,
    fiber: 10.6,
    sodium: 2,
    sugar: 0,
  }, usda(169705, "Oats (Includes foods for USDA's Food Distribution Program)")),
  food("whole-wheat-bread", "全麦面包", "staple", "grain", "两片约 60g", 60, {
    calories: 252,
    protein: 12.4,
    fat: 3.5,
    carbs: 42.7,
    fiber: 6,
    sodium: 455,
    sugar: 4.3,
  }, usda(172688, "Bread, whole-wheat, commercially prepared")),
  food("white-bread", "白吐司", "staple", "grain", "两片约 60g", 60, {
    calories: 266,
    protein: 8.8,
    fat: 3.3,
    carbs: 49.4,
    fiber: 2.7,
    sodium: 490,
    sugar: 5.7,
  }, usda(174924, "Bread, white, commercially prepared (includes soft bread crumbs)")),
  food("rye-bread", "黑麦面包", "staple", "grain", "两片约 60g", 60, {
    calories: 259,
    protein: 8.5,
    fat: 3.3,
    carbs: 48.3,
    fiber: 5.8,
    sodium: 603,
    sugar: 3.9,
  }, usda(172684, "Bread, rye")),
  food("whole-wheat-pita", "全麦皮塔饼", "staple", "grain", "一个约 70g", 70, {
    calories: 262,
    protein: 9.8,
    fat: 1.7,
    carbs: 55.9,
    fiber: 6.1,
    sodium: 421,
    sugar: 2.9,
  }, usda(174916, "Bread, pita, whole-wheat")),
  food("plain-bagel", "原味贝果", "staple", "grain", "一个约 90g", 90, {
    calories: 275,
    protein: 10.5,
    fat: 1.6,
    carbs: 53.4,
    fiber: 2.3,
    sodium: 534,
    sugar: 0,
  }, usda(175049, "Bagels, plain, enriched, without calcium propionate (includes onion, poppy, sesame)")),
  food("english-muffin", "英式松饼", "staple", "grain", "一个约 60g", 60, {
    calories: 235,
    protein: 7.7,
    fat: 1.8,
    carbs: 46,
    fiber: 2.7,
    sodium: 464,
    sugar: 0,
  }, usda(172828, "English muffins, plain, unenriched, with calcium propionate (includes sourdough)")),
  food("corn-tortilla", "玉米饼", "staple", "grain", "一张约 50g", 50, {
    calories: 222,
    protein: 5.7,
    fat: 2.5,
    carbs: 46.6,
    fiber: 5.2,
    sodium: 11,
    sugar: 0,
  }, usda(173241, "Tortillas, ready-to-bake or -fry, corn, without added salt")),
  food("wonton-wrapper", "馄饨皮", "staple", "grain", "按生皮克重估算", 40, {
    calories: 291,
    protein: 9.8,
    fat: 1.5,
    carbs: 57.9,
    fiber: 1.8,
    sodium: 572,
    sugar: 0,
  }, usda(172802, "Wonton wrappers (includes egg roll wrappers)")),
  food("potato", "土豆", "staple", "grain", "煮土豆，可作主食替换", 160, {
    calories: 87,
    protein: 1.9,
    fat: 0.1,
    carbs: 20.1,
    fiber: 1.8,
    sodium: 4,
    sugar: 0.9,
  }, usda(170438, "Potatoes, boiled, cooked in skin, flesh, without salt")),
  food("sweet-potato", "红薯", "staple", "grain", "烤红薯去皮肉，一块约 180g", 180, {
    calories: 90,
    protein: 2,
    fat: 0.1,
    carbs: 20.7,
    fiber: 3.3,
    sodium: 36,
    sugar: 6.5,
  }, usda(168483, "Sweet potato, cooked, baked in skin, flesh, without salt")),
  food("corn-kernels", "玉米粒", "staple", "grain", "熟玉米粒，一小碗约 120g", 120, {
    calories: 81,
    protein: 2.5,
    fat: 0.7,
    carbs: 19.3,
    fiber: 2.4,
    sodium: 1,
    sugar: 3.1,
  }, usda(168399, "Corn, sweet, yellow, frozen, kernels cut off cob, boiled, drained, without salt")),
  food("hominy", "玉米碱水粒", "staple", "grain", "罐装玉米碱水粒，按沥干重估算", 120, {
    calories: 72,
    protein: 1.5,
    fat: 0.9,
    carbs: 14.3,
    fiber: 2.5,
    sodium: 267,
    sugar: 1.5,
  }, usda(169701, "Hominy, canned, white")),
  food("chicken-breast", "鸡胸肉", "protein", "meat", "熟烤鸡胸，去皮肉", 120, {
    calories: 165,
    protein: 31,
    fat: 3.6,
    carbs: 0,
    fiber: 0,
    sodium: 74,
    sugar: 0,
  }, usda(171477, "Chicken, broilers or fryers, breast, meat only, cooked, roasted")),
  food("chicken-thigh", "鸡腿肉", "protein", "meat", "熟烤鸡腿肉，去皮肉", 120, {
    calories: 179,
    protein: 24.8,
    fat: 8.2,
    carbs: 0,
    fiber: 0,
    sodium: 106,
    sugar: 0,
  }, usda(172388, "Chicken, broilers or fryers, thigh, meat only, cooked, roasted")),
  food("turkey-breast", "火鸡胸肉", "protein", "meat", "熟火鸡胸肉", 120, {
    calories: 126,
    protein: 22.2,
    fat: 3.5,
    carbs: 0,
    fiber: 0,
    sodium: 397,
    sugar: 0,
  }, usda(171501, "Turkey breast, pre-basted, meat and skin, cooked, roasted")),
  food("duck-meat", "鸭肉", "protein", "meat", "熟烤鸭肉，去皮肉", 120, {
    calories: 201,
    protein: 23.5,
    fat: 11.2,
    carbs: 0,
    fiber: 0,
    sodium: 65,
    sugar: 0,
  }, usda(172411, "Duck, domesticated, meat only, cooked, roasted")),
  food("beef-sirloin", "西冷牛排", "protein", "meat", "熟牛排瘦肉，按净肉估算", 120, {
    calories: 183,
    protein: 30.6,
    fat: 5.8,
    carbs: 0,
    fiber: 0,
    sodium: 64,
    sugar: 0,
  }, usda(168634, "Beef, top sirloin, steak, separable lean only, trimmed to 0\" fat, all grades, cooked, broiled")),
  food("beef-round", "牛后腿肉", "protein", "meat", "熟烤牛后腿肉", 120, {
    calories: 167,
    protein: 29.7,
    fat: 4.5,
    carbs: 0,
    fiber: 0,
    sodium: 67,
    sugar: 0,
  }, usda(170228, "Beef, round, eye of round roast, boneless, separable lean and fat, trimmed to 0\" fat, all grades, cooked, roasted")),
  food("pork-tenderloin", "猪里脊", "protein", "meat", "熟猪里脊瘦肉", 120, {
    calories: 143,
    protein: 26.2,
    fat: 3.5,
    carbs: 0,
    fiber: 0,
    sodium: 57,
    sugar: 0,
  }, usda(168250, "Pork, fresh, loin, tenderloin, separable lean only, cooked, roasted")),
  food("pork-loin", "猪排瘦肉", "protein", "meat", "熟猪排瘦肉", 120, {
    calories: 180,
    protein: 26.8,
    fat: 7.3,
    carbs: 0,
    fiber: 0,
    sodium: 56,
    sugar: 0,
  }, usda(168240, "Pork, fresh, loin, center loin (chops), bone-in, separable lean only, cooked, broiled")),
  food("ham-slice", "火腿片", "protein", "meat", "预包装低脂火腿片", 60, {
    calories: 107,
    protein: 16.8,
    fat: 4,
    carbs: 0.7,
    fiber: 0,
    sodium: 945,
    sugar: 0,
  }, usda(173863, "Ham, sliced, pre-packaged, deli meat (96%fat free, water added)")),
  food("salmon", "三文鱼", "protein", "fish", "熟三文鱼，干热烹调", 120, {
    calories: 206,
    protein: 22.1,
    fat: 12.4,
    carbs: 0,
    fiber: 0,
    sodium: 61,
    sugar: 0,
  }, usda(175168, "Fish, salmon, Atlantic, farmed, cooked, dry heat")),
  food("cod", "鳕鱼", "protein", "fish", "熟鳕鱼，清蒸或干热做法可参考", 120, {
    calories: 84,
    protein: 20.4,
    fat: 0.2,
    carbs: 0,
    fiber: 0,
    sodium: 134,
    sugar: 0,
  }, usda(175178, "Fish, cod, Pacific, cooked")),
  food("tilapia", "罗非鱼", "protein", "fish", "熟罗非鱼，干热烹调", 120, {
    calories: 128,
    protein: 26.2,
    fat: 2.6,
    carbs: 0,
    fiber: 0,
    sodium: 56,
    sugar: 0,
  }, usda(175177, "Fish, tilapia, cooked, dry heat")),
  food("yellowfin-tuna", "黄鳍金枪鱼", "protein", "fish", "熟黄鳍金枪鱼", 120, {
    calories: 130,
    protein: 29.2,
    fat: 0.6,
    carbs: 0,
    fiber: 0,
    sodium: 54,
    sugar: 0,
  }, usda(172006, "Fish, tuna, yellowfin, fresh, cooked, dry heat")),
  food("canned-tuna", "水浸金枪鱼罐头", "protein", "fish", "沥干固形物", 100, {
    calories: 116,
    protein: 25.5,
    fat: 0.8,
    carbs: 0,
    fiber: 0,
    sodium: 50,
    sugar: 0,
  }, usda(171986, "Fish, tuna, light, canned in water, without salt, drained solids")),
  food("rainbow-trout", "虹鳟鱼", "protein", "fish", "熟虹鳟鱼，干热烹调", 120, {
    calories: 168,
    protein: 23.8,
    fat: 7.4,
    carbs: 0,
    fiber: 0,
    sodium: 61,
    sugar: 0,
  }, usda(173718, "Fish, trout, rainbow, farmed, cooked, dry heat")),
  food("catfish", "鲶鱼", "protein", "fish", "熟鲶鱼，干热烹调", 120, {
    calories: 144,
    protein: 18.4,
    fat: 7.2,
    carbs: 0,
    fiber: 0,
    sodium: 119,
    sugar: 0,
  }, usda(175166, "Fish, catfish, channel, farmed, cooked, dry heat")),
  food("mackerel", "鲭鱼", "protein", "fish", "熟鲭鱼，干热烹调", 120, {
    calories: 262,
    protein: 23.8,
    fat: 17.8,
    carbs: 0,
    fiber: 0,
    sodium: 83,
    sugar: 0,
  }, usda(175120, "Fish, mackerel, Atlantic, cooked, dry heat")),
  food("shrimp", "虾仁", "protein", "fish", "熟虾仁，湿热烹调", 100, {
    calories: 99,
    protein: 24,
    fat: 0.3,
    carbs: 0.2,
    fiber: 0,
    sodium: 111,
    sugar: 0,
  }, usda(175180, "Crustaceans, shrimp, cooked")),
  food("crab", "蟹肉", "protein", "fish", "熟蟹肉，湿热烹调", 100, {
    calories: 83,
    protein: 17.9,
    fat: 0.7,
    carbs: 0,
    fiber: 0,
    sodium: 395,
    sugar: 0,
  }, usda(174205, "Crustaceans, crab, blue, cooked, moist heat")),
  food("scallop", "扇贝", "protein", "fish", "熟蒸扇贝", 100, {
    calories: 111,
    protein: 20.5,
    fat: 0.8,
    carbs: 5.4,
    fiber: 0,
    sodium: 667,
    sugar: 0,
  }, usda(167742, "Mollusks, scallop, (bay and sea), cooked, steamed")),
  food("clam", "蛤蜊", "protein", "fish", "熟蛤蜊，湿热烹调", 100, {
    calories: 148,
    protein: 25.6,
    fat: 1.9,
    carbs: 5.1,
    fiber: 0,
    sodium: 1200,
    sugar: 0,
  }, usda(171975, "Mollusks, clam, mixed species, cooked, moist heat")),
  food("mussel", "贻贝", "protein", "fish", "熟贻贝，湿热烹调", 100, {
    calories: 172,
    protein: 23.8,
    fat: 4.5,
    carbs: 7.4,
    fiber: 0,
    sodium: 369,
    sugar: 0,
  }, usda(174217, "Mollusks, mussel, blue, cooked, moist heat")),
  food("oyster", "生蚝", "protein", "fish", "熟牡蛎，湿热烹调", 100, {
    calories: 163,
    protein: 18.9,
    fat: 4.6,
    carbs: 9.9,
    fiber: 0,
    sodium: 212,
    sugar: 0,
  }, usda(174250, "Mollusks, oyster, Pacific, cooked, moist heat")),
  food("egg", "水煮蛋", "protein", "egg", "一枚约 50g", 50, {
    calories: 155,
    protein: 12.6,
    fat: 10.6,
    carbs: 1.1,
    fiber: 0,
    sodium: 124,
    sugar: 1.1,
  }, usda(173424, "Egg, whole, cooked, hard-boiled")),
  food("egg-white", "蛋清", "protein", "egg", "一个蛋清约 30g", 60, {
    calories: 52,
    protein: 10.9,
    fat: 0.2,
    carbs: 0.7,
    fiber: 0,
    sodium: 166,
    sugar: 0.7,
  }, usda(172183, "Egg, white, raw, fresh")),
  food("tofu-firm", "北豆腐", "protein", "egg", "钙镁盐凝固的硬豆腐", 100, {
    calories: 78,
    protein: 9,
    fat: 4.2,
    carbs: 2.9,
    fiber: 0.9,
    sodium: 12,
    sugar: 0.6,
  }, usda(172448, "Tofu, firm, prepared with calcium sulfate and magnesium chloride (nigari)")),
  food("tofu-soft", "嫩豆腐", "protein", "egg", "口感更嫩，适合汤羹", 100, {
    calories: 61,
    protein: 7.2,
    fat: 3.7,
    carbs: 1.2,
    fiber: 0.2,
    sodium: 8,
    sugar: 0.7,
  }, usda(172449, "Tofu, soft, prepared with calcium sulfate and magnesium chloride (nigari)")),
  food("tempeh", "天贝", "protein", "egg", "熟天贝，植物蛋白", 100, {
    calories: 195,
    protein: 19.9,
    fat: 11.4,
    carbs: 7.6,
    fiber: 0,
    sodium: 14,
    sugar: 0,
  }, usda(172467, "Tempeh, cooked")),
  food("soybeans-cooked", "熟黄豆", "protein", "egg", "煮熟黄豆", 100, {
    calories: 172,
    protein: 18.2,
    fat: 9,
    carbs: 8.4,
    fiber: 6,
    sodium: 237,
    sugar: 2.4,
  }, usda(174299, "Soybeans, mature seeds, cooked, boiled, with salt")),
  food("kidney-beans", "红腰豆", "protein", "egg", "熟红腰豆，不加盐", 100, {
    calories: 127,
    protein: 8.7,
    fat: 0.5,
    carbs: 22.8,
    fiber: 6.4,
    sodium: 1,
    sugar: 0.3,
  }, usda(173740, "Beans, kidney, all types, mature seeds, cooked, boiled, without salt")),
  food("black-beans", "黑豆", "protein", "egg", "熟黑豆，不加盐", 100, {
    calories: 132,
    protein: 8.9,
    fat: 0.5,
    carbs: 23.7,
    fiber: 8.7,
    sodium: 1,
    sugar: 0.3,
  }, usda(173735, "Beans, black, mature seeds, cooked, boiled, without salt")),
  food("chickpeas", "鹰嘴豆", "protein", "egg", "熟鹰嘴豆，不加盐", 100, {
    calories: 164,
    protein: 8.9,
    fat: 2.6,
    carbs: 27.4,
    fiber: 7.6,
    sodium: 7,
    sugar: 4.8,
  }, usda(173757, "Chickpeas (garbanzo beans, bengal gram), mature seeds, cooked, boiled, without salt")),
  food("lentils", "扁豆", "protein", "egg", "熟扁豆，不加盐", 100, {
    calories: 116,
    protein: 9,
    fat: 0.4,
    carbs: 20.1,
    fiber: 7.9,
    sodium: 2,
    sugar: 1.8,
  }, usda(172421, "Lentils, mature seeds, cooked, boiled, without salt")),
  food("split-peas", "豌豆瓣", "protein", "egg", "熟豌豆瓣，不加盐", 100, {
    calories: 118,
    protein: 8.3,
    fat: 0.4,
    carbs: 21.1,
    fiber: 8.3,
    sodium: 2,
    sugar: 2.9,
  }, usda(172429, "Peas, split, mature seeds, cooked, boiled, without salt")),
  food("broccoli", "西兰花", "vegetable", "leaf", "生西兰花，清炒后按实际加油另计", 100, {
    calories: 34,
    protein: 2.8,
    fat: 0.4,
    carbs: 6.6,
    fiber: 2.6,
    sodium: 33,
    sugar: 1.7,
  }, usda(170379, "Broccoli, raw")),
  food("spinach", "菠菜", "vegetable", "leaf", "生菠菜，焯水后重量会变化", 100, {
    calories: 23,
    protein: 2.9,
    fat: 0.4,
    carbs: 3.6,
    fiber: 2.2,
    sodium: 79,
    sugar: 0.4,
  }, usda(168462, "Spinach, raw")),
  food("lettuce", "生菜", "vegetable", "leaf", "生食或卷饼常用", 80, {
    calories: 15,
    protein: 1.4,
    fat: 0.1,
    carbs: 2.9,
    fiber: 1.3,
    sodium: 28,
    sugar: 0.8,
  }, usda(169249, "Lettuce, green leaf, raw")),
  food("tomato", "西红柿", "vegetable", "leaf", "生西红柿", 100, {
    calories: 18,
    protein: 0.9,
    fat: 0.2,
    carbs: 3.9,
    fiber: 1.2,
    sodium: 5,
    sugar: 2.6,
  }, usda(170457, "Tomatoes, red, ripe, raw, year round average")),
  food("cucumber", "黄瓜", "vegetable", "leaf", "带皮生黄瓜", 100, {
    calories: 15,
    protein: 0.7,
    fat: 0.1,
    carbs: 3.6,
    fiber: 0.5,
    sodium: 2,
    sugar: 1.7,
  }, usda(168409, "Cucumber, with peel, raw")),
  food("cabbage", "卷心菜", "vegetable", "leaf", "生卷心菜", 100, {
    calories: 25,
    protein: 1.3,
    fat: 0.1,
    carbs: 5.8,
    fiber: 2.5,
    sodium: 18,
    sugar: 3.2,
  }, usda(169975, "Cabbage, raw")),
  food("carrot", "胡萝卜", "vegetable", "leaf", "生胡萝卜，配菜常见", 80, {
    calories: 41,
    protein: 0.9,
    fat: 0.2,
    carbs: 9.6,
    fiber: 2.8,
    sodium: 69,
    sugar: 4.7,
  }, usda(170393, "Carrots, raw")),
  food("cauliflower", "菜花", "vegetable", "leaf", "生菜花", 100, {
    calories: 25,
    protein: 1.9,
    fat: 0.3,
    carbs: 5,
    fiber: 2,
    sodium: 30,
    sugar: 1.9,
  }, usda(169986, "Cauliflower, raw")),
  food("bok-choy", "小白菜", "vegetable", "leaf", "生小白菜/上海青", 100, {
    calories: 13,
    protein: 1.5,
    fat: 0.2,
    carbs: 2.2,
    fiber: 1,
    sodium: 65,
    sugar: 1.2,
  }, usda(170390, "Cabbage, chinese (pak-choi), raw")),
  food("kale", "羽衣甘蓝", "vegetable", "leaf", "生羽衣甘蓝", 80, {
    calories: 35,
    protein: 2.9,
    fat: 1.5,
    carbs: 4.4,
    fiber: 4.1,
    sodium: 53,
    sugar: 1,
  }, usda(168421, "Kale, raw")),
  food("asparagus", "芦笋", "vegetable", "leaf", "熟芦笋，水煮沥干", 100, {
    calories: 22,
    protein: 2.4,
    fat: 0.2,
    carbs: 4.1,
    fiber: 2,
    sodium: 14,
    sugar: 1.3,
  }, usda(168390, "Asparagus, cooked, boiled, drained")),
  food("eggplant", "茄子", "vegetable", "leaf", "熟茄子，水煮沥干", 120, {
    calories: 35,
    protein: 0.8,
    fat: 0.2,
    carbs: 8.7,
    fiber: 2.5,
    sodium: 1,
    sugar: 3.2,
  }, usda(169229, "Eggplant, cooked, boiled, drained, without salt")),
  food("red-bell-pepper", "红甜椒", "vegetable", "leaf", "生红甜椒", 100, {
    calories: 26,
    protein: 1,
    fat: 0.3,
    carbs: 6,
    fiber: 2.1,
    sodium: 4,
    sugar: 4.2,
  }, usda(170108, "Peppers, sweet, red, raw")),
  food("onion", "洋葱", "vegetable", "leaf", "生洋葱", 80, {
    calories: 40,
    protein: 1.1,
    fat: 0.1,
    carbs: 9.3,
    fiber: 1.7,
    sodium: 4,
    sugar: 4.2,
  }, usda(170000, "Onions, raw")),
  food("celery", "西芹", "vegetable", "leaf", "生西芹", 80, {
    calories: 14,
    protein: 0.7,
    fat: 0.2,
    carbs: 3,
    fiber: 1.6,
    sodium: 80,
    sugar: 1.3,
  }, usda(169988, "Celery, raw")),
  food("green-peas", "青豆", "vegetable", "leaf", "熟青豆，水煮沥干", 100, {
    calories: 78,
    protein: 5.2,
    fat: 0.3,
    carbs: 14.3,
    fiber: 4.5,
    sodium: 72,
    sugar: 4.4,
  }, usda(170017, "Peas, green, frozen, cooked, boiled, drained, without salt")),
  food("green-beans", "四季豆", "vegetable", "leaf", "熟四季豆，水煮沥干", 100, {
    calories: 35,
    protein: 1.9,
    fat: 0.3,
    carbs: 7.9,
    fiber: 3.2,
    sodium: 1,
    sugar: 3.6,
  }, usda(169141, "Beans, snap, green, cooked, boiled, drained, without salt")),
  food("brussels-sprouts", "抱子甘蓝", "vegetable", "leaf", "熟抱子甘蓝，水煮沥干", 100, {
    calories: 36,
    protein: 2.5,
    fat: 0.5,
    carbs: 7.1,
    fiber: 2.6,
    sodium: 21,
    sugar: 1.7,
  }, usda(169971, "Brussels sprouts, cooked, boiled, drained, without salt")),
  food("beetroot", "甜菜根", "vegetable", "leaf", "熟甜菜根，水煮沥干", 100, {
    calories: 44,
    protein: 1.7,
    fat: 0.2,
    carbs: 10,
    fiber: 2,
    sodium: 77,
    sugar: 8,
  }, usda(169146, "Beets, cooked, boiled, drained")),
  food("pumpkin", "南瓜", "vegetable", "leaf", "熟南瓜，水煮沥干", 150, {
    calories: 20,
    protein: 0.7,
    fat: 0.1,
    carbs: 4.9,
    fiber: 1.1,
    sodium: 1,
    sugar: 2.1,
  }, usda(168449, "Pumpkin, cooked, boiled, drained, without salt")),
  food("white-mushroom", "白蘑菇", "vegetable", "leaf", "生白蘑菇", 80, {
    calories: 22,
    protein: 3.1,
    fat: 0.3,
    carbs: 3.3,
    fiber: 1,
    sodium: 5,
    sugar: 2,
  }, usda(169251, "Mushrooms, white, raw")),
  food("portabella-mushroom", "褐蘑菇", "vegetable", "leaf", "烤褐蘑菇", 80, {
    calories: 29,
    protein: 3.3,
    fat: 0.6,
    carbs: 4.4,
    fiber: 2.2,
    sodium: 11,
    sugar: 2.3,
  }, usda(169243, "Mushrooms, portabella, grilled")),
  food("shiitake", "香菇", "vegetable", "leaf", "熟香菇，不加盐", 80, {
    calories: 56,
    protein: 1.6,
    fat: 0.2,
    carbs: 14.4,
    fiber: 2.1,
    sodium: 4,
    sugar: 3.8,
  }, usda(168437, "Mushrooms, shiitake, cooked, without salt")),
  food("cilantro", "香菜", "vegetable", "leaf", "生香菜，少量配菜", 10, {
    calories: 23,
    protein: 2.1,
    fat: 0.5,
    carbs: 3.7,
    fiber: 2.8,
    sodium: 46,
    sugar: 0.9,
  }, usda(169997, "Coriander (cilantro) leaves, raw")),
  food("parsley", "欧芹", "vegetable", "leaf", "新鲜欧芹，少量配菜", 10, {
    calories: 36,
    protein: 3,
    fat: 0.8,
    carbs: 6.3,
    fiber: 3.3,
    sodium: 56,
    sugar: 0.8,
  }, usda(170416, "Parsley, fresh")),
  food("garlic", "大蒜", "vegetable", "leaf", "生大蒜，调味用量另计", 10, {
    calories: 149,
    protein: 6.4,
    fat: 0.5,
    carbs: 33.1,
    fiber: 2.1,
    sodium: 17,
    sugar: 1,
  }, usda(169230, "Garlic, raw")),
  food("ginger", "生姜", "vegetable", "leaf", "生姜，调味用量另计", 10, {
    calories: 80,
    protein: 1.8,
    fat: 0.8,
    carbs: 17.8,
    fiber: 2,
    sodium: 13,
    sugar: 1.7,
  }, usda(169231, "Ginger root, raw")),
  food("kelp", "海带", "vegetable", "leaf", "生海带，钠含量较高", 50, {
    calories: 43,
    protein: 1.7,
    fat: 0.6,
    carbs: 9.6,
    fiber: 1.3,
    sodium: 233,
    sugar: 0.6,
  }, usda(168457, "Seaweed, kelp, raw")),
  food("okra", "秋葵", "vegetable", "leaf", "熟秋葵，水煮沥干", 100, {
    calories: 22,
    protein: 1.9,
    fat: 0.2,
    carbs: 4.5,
    fiber: 2.5,
    sodium: 6,
    sugar: 2.4,
  }, usda(169261, "Okra, cooked, boiled, drained, without salt")),
  food("radish", "水萝卜", "vegetable", "leaf", "生水萝卜", 80, {
    calories: 16,
    protein: 0.7,
    fat: 0.1,
    carbs: 3.4,
    fiber: 1.6,
    sodium: 39,
    sugar: 1.9,
  }, usda(169276, "Radishes, raw")),
  food("sweet-potato-leaves", "红薯叶", "vegetable", "leaf", "熟红薯叶，蒸熟不加盐", 100, {
    calories: 35,
    protein: 2.2,
    fat: 0.3,
    carbs: 7.4,
    fiber: 1.9,
    sodium: 7,
    sugar: 5.5,
  }, usda(169304, "Sweet potato leaves, cooked, steamed, without salt")),
  food("apple", "苹果", "fruit", "fruit", "带皮苹果，一个中等约 180g", 180, {
    calories: 52,
    protein: 0.3,
    fat: 0.2,
    carbs: 13.8,
    fiber: 2.4,
    sodium: 1,
    sugar: 10.4,
  }, usda(171688, "Apples, raw, with skin (Includes foods for USDA's Food Distribution Program)")),
  food("fuji-apple", "富士苹果", "fruit", "fruit", "带皮富士苹果", 180, {
    calories: 63,
    protein: 0.2,
    fat: 0.2,
    carbs: 15.2,
    fiber: 2.1,
    sodium: 1,
    sugar: 11.7,
  }, usda(167793, "Apples, raw, fuji, with skin (Includes foods for USDA's Food Distribution Program)")),
  food("banana", "香蕉", "fruit", "fruit", "一根中等约 120g", 120, {
    calories: 89,
    protein: 1.1,
    fat: 0.3,
    carbs: 22.8,
    fiber: 2.6,
    sodium: 1,
    sugar: 12.2,
  }, usda(173944, "Bananas, raw")),
  food("blueberry", "蓝莓", "fruit", "fruit", "一小盒约 80g", 80, {
    calories: 57,
    protein: 0.7,
    fat: 0.3,
    carbs: 14.5,
    fiber: 2.4,
    sodium: 1,
    sugar: 10,
  }, usda(171711, "Blueberries, raw")),
  food("orange", "橙子", "fruit", "fruit", "一个约 180g", 180, {
    calories: 47,
    protein: 0.9,
    fat: 0.1,
    carbs: 11.8,
    fiber: 2.4,
    sodium: 0,
    sugar: 9.3,
  }, usda(169097, "Oranges, raw, all commercial varieties")),
  food("kiwi", "猕猴桃", "fruit", "fruit", "一个约 100g", 100, {
    calories: 61,
    protein: 1.1,
    fat: 0.5,
    carbs: 14.7,
    fiber: 3,
    sodium: 3,
    sugar: 9,
  }, usda(168153, "Kiwifruit, green, raw")),
  food("strawberry", "草莓", "fruit", "fruit", "一小碗约 100g", 100, {
    calories: 32,
    protein: 0.7,
    fat: 0.3,
    carbs: 7.7,
    fiber: 2,
    sodium: 1,
    sugar: 4.9,
  }, usda(167762, "Strawberries, raw")),
  food("pear", "梨", "fruit", "fruit", "一个中等约 180g", 180, {
    calories: 57,
    protein: 0.4,
    fat: 0.1,
    carbs: 15.2,
    fiber: 3.1,
    sodium: 1,
    sugar: 9.8,
  }, usda(169118, "Pears, raw")),
  food("grapefruit", "西柚", "fruit", "fruit", "半个到一个约 180g", 180, {
    calories: 32,
    protein: 0.6,
    fat: 0.1,
    carbs: 8.1,
    fiber: 1.1,
    sodium: 0,
    sugar: 7,
  }, usda(173033, "Grapefruit, raw, pink and red and white, all areas")),
  food("watermelon", "西瓜", "fruit", "fruit", "一块约 200g", 200, {
    calories: 30,
    protein: 0.6,
    fat: 0.1,
    carbs: 7.5,
    fiber: 0.4,
    sodium: 1,
    sugar: 6.2,
  }, usda(167765, "Watermelon, raw")),
  food("grapes", "葡萄", "fruit", "fruit", "一小串约 120g", 120, {
    calories: 69,
    protein: 0.7,
    fat: 0.2,
    carbs: 18.1,
    fiber: 0.9,
    sodium: 2,
    sugar: 15.5,
  }, usda(174683, "Grapes, red or green (European type, such as Thompson seedless), raw")),
  food("mango", "芒果", "fruit", "fruit", "果肉约 150g", 150, {
    calories: 60,
    protein: 0.8,
    fat: 0.4,
    carbs: 15,
    fiber: 1.6,
    sodium: 1,
    sugar: 13.7,
  }, usda(169910, "Mangos, raw")),
  food("pineapple", "菠萝", "fruit", "fruit", "切块约 150g", 150, {
    calories: 50,
    protein: 0.5,
    fat: 0.1,
    carbs: 13.1,
    fiber: 1.4,
    sodium: 1,
    sugar: 9.8,
  }, usda(169124, "Pineapple, raw, all varieties")),
  food("peach", "桃子", "fruit", "fruit", "一个约 150g", 150, {
    calories: 39,
    protein: 0.9,
    fat: 0.2,
    carbs: 9.5,
    fiber: 1.5,
    sodium: 0,
    sugar: 8.4,
  }, usda(169928, "Peaches, yellow, raw")),
  food("plum", "李子", "fruit", "fruit", "两个小李子约 100g", 100, {
    calories: 46,
    protein: 0.7,
    fat: 0.3,
    carbs: 11.4,
    fiber: 1.4,
    sodium: 0,
    sugar: 9.9,
  }, usda(169949, "Plums, raw")),
  food("cherry", "樱桃", "fruit", "fruit", "一小碗约 100g", 100, {
    calories: 63,
    protein: 1.1,
    fat: 0.2,
    carbs: 16,
    fiber: 2.1,
    sodium: 0,
    sugar: 12.8,
  }, usda(171719, "Cherries, sweet, raw")),
  food("raspberry", "树莓", "fruit", "fruit", "一小盒约 80g", 80, {
    calories: 52,
    protein: 1.2,
    fat: 0.7,
    carbs: 11.9,
    fiber: 6.5,
    sodium: 1,
    sugar: 4.4,
  }, usda(167755, "Raspberries, raw")),
  food("blackberry", "黑莓", "fruit", "fruit", "一小盒约 80g", 80, {
    calories: 43,
    protein: 1.4,
    fat: 0.5,
    carbs: 9.6,
    fiber: 5.3,
    sodium: 1,
    sugar: 4.9,
  }, usda(173946, "Blackberries, raw")),
  food("cantaloupe", "哈密瓜", "fruit", "fruit", "切块约 150g", 150, {
    calories: 34,
    protein: 0.8,
    fat: 0.2,
    carbs: 8.2,
    fiber: 0.9,
    sodium: 16,
    sugar: 7.9,
  }, usda(169092, "Melons, cantaloupe, raw")),
  food("honeydew", "蜜瓜", "fruit", "fruit", "切块约 150g", 150, {
    calories: 36,
    protein: 0.5,
    fat: 0.1,
    carbs: 9.1,
    fiber: 0.8,
    sodium: 18,
    sugar: 8.1,
  }, usda(169911, "Melons, honeydew, raw")),
  food("papaya", "木瓜", "fruit", "fruit", "切块约 150g", 150, {
    calories: 43,
    protein: 0.5,
    fat: 0.3,
    carbs: 10.8,
    fiber: 1.7,
    sodium: 8,
    sugar: 7.8,
  }, usda(169926, "Papayas, raw")),
  food("pomegranate", "石榴", "fruit", "fruit", "籽粒约 100g", 100, {
    calories: 83,
    protein: 1.7,
    fat: 1.2,
    carbs: 18.7,
    fiber: 4,
    sodium: 3,
    sugar: 13.7,
  }, usda(169134, "Pomegranates, raw")),
  food("avocado", "牛油果", "fruit", "fruit", "半个约 100g", 100, {
    calories: 160,
    protein: 2,
    fat: 14.7,
    carbs: 8.5,
    fiber: 6.7,
    sodium: 7,
    sugar: 0.7,
  }, usda(171705, "Avocados, raw, all commercial varieties")),
  food("lemon", "柠檬", "fruit", "fruit", "不带皮柠檬肉", 50, {
    calories: 29,
    protein: 1.1,
    fat: 0.3,
    carbs: 9.3,
    fiber: 2.8,
    sodium: 2,
    sugar: 2.5,
  }, usda(167746, "Lemons, raw, without peel")),
  food("lime", "青柠", "fruit", "fruit", "一个可食部约 50g", 50, {
    calories: 30,
    protein: 0.7,
    fat: 0.2,
    carbs: 10.5,
    fiber: 2.8,
    sodium: 2,
    sugar: 1.7,
  }, usda(168155, "Limes, raw")),
  food("dates", "椰枣", "fruit", "fruit", "干果糖分高，小份量", 25, {
    calories: 282,
    protein: 2.5,
    fat: 0.4,
    carbs: 75,
    fiber: 8,
    sodium: 2,
    sugar: 63.4,
  }, usda(171726, "Dates, deglet noor")),
  food("raisins", "葡萄干", "fruit", "fruit", "干果糖分高，小份量", 25, {
    calories: 299,
    protein: 3.3,
    fat: 0.2,
    carbs: 79.3,
    fiber: 4.5,
    sodium: 26,
    sugar: 65.2,
  }, usda(168165, "Raisins, dark, seedless (Includes foods for USDA's Food Distribution Program)")),
  food("fig", "无花果", "fruit", "fruit", "新鲜无花果", 80, {
    calories: 74,
    protein: 0.8,
    fat: 0.3,
    carbs: 19.2,
    fiber: 2.9,
    sodium: 1,
    sugar: 16.3,
  }, usda(173021, "Figs, raw")),
  food("mandarin", "橘子", "fruit", "fruit", "一个约 120g", 120, {
    calories: 53,
    protein: 0.8,
    fat: 0.3,
    carbs: 13.3,
    fiber: 1.8,
    sodium: 2,
    sugar: 10.6,
  }, usda(169105, "Tangerines, (mandarin oranges), raw")),
  food("whole-milk", "全脂牛奶", "dairy", "drop", "一杯约 250g", 250, {
    calories: 61,
    protein: 3.1,
    fat: 3.2,
    carbs: 4.8,
    fiber: 0,
    sodium: 43,
    sugar: 5,
  }, usda(171265, "Milk, whole, 3.25% milkfat, with added vitamin D")),
  food("reduced-fat-milk", "低脂牛奶 2%", "dairy", "drop", "一杯约 250g", 250, {
    calories: 50,
    protein: 3.3,
    fat: 2,
    carbs: 4.8,
    fiber: 0,
    sodium: 47,
    sugar: 5.1,
  }, usda(171267, "Milk, reduced fat, fluid, 2% milkfat, with added vitamin A and vitamin D")),
  food("milk", "低脂牛奶 1%", "dairy", "drop", "一杯约 250g", 250, {
    calories: 42,
    protein: 3.4,
    fat: 1,
    carbs: 5,
    fiber: 0,
    sodium: 44,
    sugar: 5.2,
  }, usda(170872, "Milk, lowfat, fluid, 1% milkfat, with added vitamin A and vitamin D")),
  food("skim-milk", "脱脂牛奶", "dairy", "drop", "一杯约 250g", 250, {
    calories: 34,
    protein: 3.4,
    fat: 0.1,
    carbs: 5,
    fiber: 0,
    sodium: 42,
    sugar: 5.1,
  }, usda(171269, "Milk, nonfat, fluid, with added vitamin A and vitamin D (fat free or skim)")),
  food("soymilk", "豆奶", "dairy", "drop", "一杯约 250g", 250, {
    calories: 43,
    protein: 2.6,
    fat: 1.5,
    carbs: 4.9,
    fiber: 0.2,
    sodium: 47,
    sugar: 3.6,
  }, usda(172456, "Soymilk, original and vanilla, with added calcium, vitamins A and D")),
  food("almond-milk", "无糖杏仁奶", "dairy", "drop", "一杯约 250g", 250, {
    calories: 15,
    protein: 0.4,
    fat: 1,
    carbs: 1.3,
    fiber: 0.2,
    sodium: 72,
    sugar: 0.8,
  }, usda(174832, "Beverages, almond milk, unsweetened, shelf stable")),
  food("yogurt-lowfat", "低脂原味酸奶", "dairy", "drop", "一杯约 180g", 180, {
    calories: 63,
    protein: 5.2,
    fat: 1.6,
    carbs: 7,
    fiber: 0,
    sodium: 70,
    sugar: 7,
  }, usda(170886, "Yogurt, plain, low fat")),
  food("yogurt-skim", "脱脂原味酸奶", "dairy", "drop", "一杯约 180g", 180, {
    calories: 56,
    protein: 5.7,
    fat: 0.2,
    carbs: 7.7,
    fiber: 0,
    sodium: 77,
    sugar: 7.7,
  }, usda(170887, "Yogurt, plain, skim milk")),
  food("greek-yogurt", "希腊酸奶脱脂", "dairy", "drop", "一杯约 150g", 150, {
    calories: 59,
    protein: 10.2,
    fat: 0.4,
    carbs: 3.6,
    fiber: 0,
    sodium: 36,
    sugar: 3.2,
  }, usda(170894, "Yogurt, Greek, plain, nonfat (Includes foods for USDA's Food Distribution Program)")),
  food("greek-yogurt-lowfat", "希腊酸奶低脂", "dairy", "drop", "一杯约 150g", 150, {
    calories: 73,
    protein: 9.9,
    fat: 1.9,
    carbs: 3.9,
    fiber: 0,
    sodium: 34,
    sugar: 3.6,
  }, usda(170903, "Yogurt, Greek, plain, lowfat")),
  food("greek-yogurt-whole", "希腊酸奶全脂", "dairy", "drop", "一杯约 150g", 150, {
    calories: 97,
    protein: 9,
    fat: 5,
    carbs: 4,
    fiber: 0,
    sodium: 35,
    sugar: 4,
  }, usda(171304, "Yogurt, Greek, plain, whole milk")),
  food("cottage-cheese", "茅屋奶酪", "dairy", "drop", "半杯约 110g", 110, {
    calories: 81,
    protein: 10.4,
    fat: 2.3,
    carbs: 4.8,
    fiber: 0,
    sodium: 308,
    sugar: 4,
  }, usda(172182, "Cheese, cottage, lowfat, 2% milkfat")),
  food("cheddar", "切达奶酪", "dairy", "drop", "一片约 30g", 30, {
    calories: 403,
    protein: 22.9,
    fat: 33.3,
    carbs: 3.4,
    fiber: 0,
    sodium: 653,
    sugar: 0.5,
  }, usda(173414, "Cheese, cheddar (Includes foods for USDA's Food Distribution Program)")),
  food("mozzarella", "马苏里拉奶酪", "dairy", "drop", "一片约 30g", 30, {
    calories: 295,
    protein: 23.8,
    fat: 19.8,
    carbs: 5.6,
    fiber: 0,
    sodium: 666,
    sugar: 1.9,
  }, usda(171244, "Cheese, mozzarella, low moisture, part-skim")),
  food("feta", "菲达奶酪", "dairy", "drop", "一小块约 30g", 30, {
    calories: 265,
    protein: 14.2,
    fat: 21.5,
    carbs: 3.9,
    fiber: 0,
    sodium: 1140,
    sugar: 0,
  }, usda(173420, "Cheese, feta")),
  food("parmesan", "帕玛森奶酪", "dairy", "drop", "磨碎少量约 10g", 10, {
    calories: 392,
    protein: 35.8,
    fat: 25,
    carbs: 3.2,
    fiber: 0,
    sodium: 1180,
    sugar: 0.1,
  }, usda(170848, "Cheese, parmesan, hard")),
  food("whey-protein", "乳清蛋白粉", "dairy", "drop", "一勺约 30g", 30, {
    calories: 359,
    protein: 58.1,
    fat: 1.2,
    carbs: 29.1,
    fiber: 0,
    sodium: 372,
    sugar: 1.2,
  }, usda(173177, "Beverages, Whey protein powder isolate")),
  food("kefir", "低脂开菲尔", "dairy", "drop", "一杯约 250g", 250, {
    calories: 43,
    protein: 3.8,
    fat: 1,
    carbs: 4.8,
    fiber: 0,
    sodium: 40,
    sugar: 4.6,
  }, usda(170904, "Kefir, lowfat, plain, LIFEWAY")),
  food("almond", "杏仁", "snack", "cookie", "一小把约 25g", 25, {
    calories: 579,
    protein: 21.2,
    fat: 49.9,
    carbs: 21.6,
    fiber: 12.5,
    sodium: 1,
    sugar: 4.3,
  }, usda(170567, "Nuts, almonds")),
  food("walnut", "核桃", "snack", "cookie", "一小把约 25g", 25, {
    calories: 654,
    protein: 15.2,
    fat: 65.2,
    carbs: 13.7,
    fiber: 6.7,
    sodium: 2,
    sugar: 2.6,
  }, usda(170187, "Nuts, walnuts, english")),
  food("cashew", "腰果", "snack", "cookie", "一小把约 25g", 25, {
    calories: 553,
    protein: 18.2,
    fat: 43.8,
    carbs: 30.2,
    fiber: 3.3,
    sodium: 12,
    sugar: 5.9,
  }, usda(170162, "Nuts, cashew nuts, raw")),
  food("pistachio", "开心果", "snack", "cookie", "一小把约 25g", 25, {
    calories: 560,
    protein: 20.2,
    fat: 45.3,
    carbs: 27.2,
    fiber: 10.6,
    sodium: 1,
    sugar: 7.7,
  }, usda(170184, "Nuts, pistachio nuts, raw")),
  food("peanut", "花生", "snack", "cookie", "一小把约 25g", 25, {
    calories: 567,
    protein: 25.8,
    fat: 49.2,
    carbs: 16.1,
    fiber: 8.5,
    sodium: 18,
    sugar: 4.7,
  }, usda(172430, "Peanuts, all types, raw")),
  food("hazelnut", "榛子", "snack", "cookie", "一小把约 25g", 25, {
    calories: 628,
    protein: 15,
    fat: 60.8,
    carbs: 16.7,
    fiber: 9.7,
    sodium: 0,
    sugar: 4.3,
  }, usda(170581, "Nuts, hazelnuts or filberts")),
  food("pecan", "碧根果", "snack", "cookie", "一小把约 25g", 25, {
    calories: 691,
    protein: 9.2,
    fat: 72,
    carbs: 13.9,
    fiber: 9.6,
    sodium: 0,
    sugar: 4,
  }, usda(170182, "Nuts, pecans")),
  food("macadamia", "夏威夷果", "snack", "cookie", "一小把约 25g", 25, {
    calories: 718,
    protein: 7.9,
    fat: 75.8,
    carbs: 13.8,
    fiber: 8.6,
    sodium: 5,
    sugar: 4.6,
  }, usda(170178, "Nuts, macadamia nuts, raw")),
  food("sunflower-seeds", "葵花籽仁", "snack", "cookie", "去壳籽仁，约 20g", 20, {
    calories: 619,
    protein: 17.2,
    fat: 56.8,
    carbs: 20.6,
    fiber: 11.5,
    sodium: 3,
    sugar: 0,
  }, usda(170154, "Seeds, sunflower seed kernels, toasted, without salt")),
  food("pumpkin-seeds", "南瓜籽仁", "snack", "cookie", "去壳籽仁，约 20g", 20, {
    calories: 559,
    protein: 30.2,
    fat: 49,
    carbs: 10.7,
    fiber: 6,
    sodium: 7,
    sugar: 1.4,
  }, usda(170556, "Seeds, pumpkin and squash seed kernels, dried")),
  food("sesame-seeds", "芝麻", "snack", "cookie", "撒料少量约 10g", 10, {
    calories: 573,
    protein: 17.7,
    fat: 49.7,
    carbs: 23.4,
    fiber: 11.8,
    sodium: 11,
    sugar: 0.3,
  }, usda(170150, "Seeds, sesame seeds, whole, dried")),
  food("chia-seeds", "奇亚籽", "snack", "cookie", "一勺约 12g", 12, {
    calories: 486,
    protein: 16.5,
    fat: 30.7,
    carbs: 42.1,
    fiber: 34.4,
    sodium: 16,
    sugar: 0,
  }, usda(170554, "Seeds, chia seeds, dried")),
  food("flaxseed", "亚麻籽", "snack", "cookie", "一勺约 10g", 10, {
    calories: 534,
    protein: 18.3,
    fat: 42.2,
    carbs: 28.9,
    fiber: 27.3,
    sodium: 30,
    sugar: 1.6,
  }, usda(169414, "Seeds, flaxseed")),
  food("hummus", "鹰嘴豆泥", "snack", "cookie", "蘸酱小份约 40g", 40, {
    calories: 177,
    protein: 4.9,
    fat: 8.6,
    carbs: 20.1,
    fiber: 4,
    sodium: 242,
    sugar: 0.3,
  }, usda(172454, "Hummus, home prepared")),
  food("peanut-butter", "花生酱", "snack", "cookie", "一勺约 16g", 16, {
    calories: 598,
    protein: 22.2,
    fat: 51.4,
    carbs: 22.3,
    fiber: 5,
    sodium: 17,
    sugar: 10.5,
  }, usda(172470, "Peanut butter, smooth style, without salt")),
  food("popcorn", "空气爆米花", "snack", "cookie", "无盐空气爆版本", 30, {
    calories: 382,
    protein: 12,
    fat: 4.2,
    carbs: 77.9,
    fiber: 15.1,
    sodium: 4,
    sugar: 0,
  }, usda(170246, "Snacks, popcorn, air-popped (Unsalted)")),
  food("rice-cake", "糙米米饼", "snack", "cookie", "一片约 9g", 18, {
    calories: 387,
    protein: 8.2,
    fat: 2.8,
    carbs: 81.5,
    fiber: 4.2,
    sodium: 26,
    sugar: 0.9,
  }, usda(170250, "Snacks, rice cakes, brown rice, plain, unsalted")),
  food("dark-chocolate", "黑巧克力", "snack", "cookie", "70-85% 可可，小块约 20g", 20, {
    calories: 598,
    protein: 7.8,
    fat: 42.6,
    carbs: 45.9,
    fiber: 10.9,
    sodium: 20,
    sugar: 24,
  }, usda(170273, "Chocolate, dark, 70-85% cacao solids")),
  food("dried-apricot", "杏干", "snack", "cookie", "干果小份约 25g", 25, {
    calories: 241,
    protein: 3.4,
    fat: 0.5,
    carbs: 62.6,
    fiber: 7.3,
    sodium: 10,
    sugar: 53.4,
  }, usda(173941, "Apricots, dried, sulfured, uncooked")),
  food("trail-mix", "混合坚果果干", "snack", "cookie", "无盐综合混合，一小把约 30g", 30, {
    calories: 462,
    protein: 13.8,
    fat: 29.4,
    carbs: 44.9,
    fiber: 0,
    sodium: 10,
    sugar: 0,
  }, usda(170654, "Snacks, trail mix, regular, unsalted")),
  food("granola", "格兰诺拉", "snack", "cookie", "早餐搭配酸奶，约 40g", 40, {
    calories: 489,
    protein: 13.7,
    fat: 24.3,
    carbs: 53.9,
    fiber: 8.9,
    sodium: 26,
    sugar: 19.8,
  }, usda(171646, "Cereals ready-to-eat, granola, homemade")),
  food("olive-oil", "橄榄油", "condiment", "drop", "炒菜或沙拉，一勺约 10g", 10, {
    calories: 884,
    protein: 0,
    fat: 100,
    carbs: 0,
    fiber: 0,
    sodium: 2,
    sugar: 0,
  }, usda(171413, "Oil, olive, salad or cooking")),
  food("canola-oil", "菜籽油", "condiment", "drop", "炒菜用油，一勺约 10g", 10, {
    calories: 884,
    protein: 0,
    fat: 100,
    carbs: 0,
    fiber: 0,
    sodium: 0,
    sugar: 0,
  }, usda(172336, "Oil, canola")),
  food("soybean-oil", "大豆油", "condiment", "drop", "炒菜用油，一勺约 10g", 10, {
    calories: 884,
    protein: 0,
    fat: 100,
    carbs: 0,
    fiber: 0,
    sodium: 0,
    sugar: 0,
  }, usda(171411, "Oil, soybean, salad or cooking")),
  food("sesame-oil", "芝麻油", "condiment", "drop", "提香用量通常较小", 5, {
    calories: 884,
    protein: 0,
    fat: 100,
    carbs: 0,
    fiber: 0,
    sodium: 0,
    sugar: 0,
  }, usda(171016, "Oil, sesame, salad or cooking")),
  food("peanut-oil", "花生油", "condiment", "drop", "炒菜用油，一勺约 10g", 10, {
    calories: 884,
    protein: 0,
    fat: 100,
    carbs: 0,
    fiber: 0,
    sodium: 0,
    sugar: 0,
  }, usda(171410, "Oil, peanut, salad or cooking")),
  food("butter", "黄油", "condiment", "drop", "一小块约 10g", 10, {
    calories: 717,
    protein: 0.8,
    fat: 81.1,
    carbs: 0.1,
    fiber: 0,
    sodium: 643,
    sugar: 0.1,
  }, usda(173410, "Butter, salted")),
  food("soy-sauce", "酱油", "condiment", "drop", "普通酱油，钠含量高", 10, {
    calories: 53,
    protein: 8.1,
    fat: 0.6,
    carbs: 4.9,
    fiber: 0.8,
    sodium: 5490,
    sugar: 0.4,
  }, usda(174277, "Soy sauce made from soy and wheat (shoyu)")),
  food("low-sodium-soy-sauce", "低钠酱油", "condiment", "drop", "低钠酱油，用量仍需控制", 10, {
    calories: 57,
    protein: 9.1,
    fat: 0.3,
    carbs: 5.6,
    fiber: 0.7,
    sodium: 3600,
    sugar: 0.5,
  }, usda(172473, "Soy sauce made from soy and wheat (shoyu), low sodium")),
  food("distilled-vinegar", "白醋", "condiment", "drop", "调味少量使用", 10, {
    calories: 18,
    protein: 0,
    fat: 0,
    carbs: 0,
    fiber: 0,
    sodium: 2,
    sugar: 0,
  }, usda(172237, "Vinegar, distilled")),
  food("balsamic-vinegar", "香醋/黑醋", "condiment", "drop", "沙拉或蘸料少量使用", 10, {
    calories: 88,
    protein: 0.5,
    fat: 0,
    carbs: 17,
    fiber: 0,
    sodium: 23,
    sugar: 15,
  }, usda(172241, "Vinegar, balsamic")),
  food("salt", "食盐", "condiment", "drop", "钠含量极高，按克记录", 2, {
    calories: 0,
    protein: 0,
    fat: 0,
    carbs: 0,
    fiber: 0,
    sodium: 38800,
    sugar: 0,
  }, usda(173468, "Salt, table")),
  food("ketchup", "番茄酱", "condiment", "drop", "蘸料一小包约 15g", 15, {
    calories: 101,
    protein: 1,
    fat: 0.1,
    carbs: 27.4,
    fiber: 0.3,
    sodium: 907,
    sugar: 21.3,
  }, usda(168556, "Catsup")),
  food("mustard", "黄芥末酱", "condiment", "drop", "蘸料少量使用", 10, {
    calories: 60,
    protein: 3.7,
    fat: 3.3,
    carbs: 5.8,
    fiber: 4,
    sodium: 1100,
    sugar: 0.9,
  }, usda(172234, "Mustard, prepared, yellow")),
  food("mayonnaise", "蛋黄酱", "condiment", "drop", "脂肪较高，一勺约 15g", 15, {
    calories: 680,
    protein: 1,
    fat: 74.8,
    carbs: 0.6,
    fiber: 0,
    sodium: 635,
    sugar: 0.6,
  }, usda(171009, "Salad dressing, mayonnaise, regular")),
  food("italian-dressing", "意式沙拉汁", "condiment", "drop", "沙拉调味，一勺约 15g", 15, {
    calories: 240,
    protein: 0.4,
    fat: 21.1,
    carbs: 12.1,
    fiber: 0,
    sodium: 993,
    sugar: 10.8,
  }, usda(171019, "Salad dressing, italian dressing, commercial, regular")),
  food("salsa", "莎莎酱", "condiment", "drop", "蘸料或卷饼配料", 30, {
    calories: 29,
    protein: 1.5,
    fat: 0.2,
    carbs: 6.6,
    fiber: 1.9,
    sodium: 711,
    sugar: 4,
  }, usda(174524, "Sauce, salsa, ready-to-serve")),
  food("teriyaki-sauce", "照烧汁", "condiment", "drop", "甜咸酱汁，注意钠和糖", 15, {
    calories: 89,
    protein: 5.9,
    fat: 0,
    carbs: 15.6,
    fiber: 0.1,
    sodium: 3830,
    sugar: 14.1,
  }, usda(171167, "Sauce, teriyaki, ready-to-serve")),
  food("barbecue-sauce", "烧烤酱", "condiment", "drop", "甜咸酱汁，注意糖", 15, {
    calories: 172,
    protein: 0.8,
    fat: 0.6,
    carbs: 40.8,
    fiber: 0.9,
    sodium: 1030,
    sugar: 33.2,
  }, usda(174523, "Sauce, barbecue")),
  food("honey", "蜂蜜", "condiment", "drop", "一小勺约 10g", 10, {
    calories: 304,
    protein: 0.3,
    fat: 0,
    carbs: 82.4,
    fiber: 0.2,
    sodium: 4,
    sugar: 82.1,
  }, usda(169640, "Honey")),
  food("sugar", "白砂糖", "condiment", "drop", "按实际克重记录", 5, {
    calories: 387,
    protein: 0,
    fat: 0,
    carbs: 100,
    fiber: 0,
    sodium: 1,
    sugar: 99.8,
  }, usda(169655, "Sugars, granulated")),
  food("miso", "味噌", "condiment", "drop", "汤底和调味常见，钠较高", 15, {
    calories: 198,
    protein: 12.8,
    fat: 6,
    carbs: 25.4,
    fiber: 5.4,
    sodium: 3730,
    sugar: 6.2,
  }, usda(172442, "Miso")),
  food("fish-sauce", "鱼露", "condiment", "drop", "咸鲜调味，钠含量高", 5, {
    calories: 35,
    protein: 5.1,
    fat: 0,
    carbs: 3.6,
    fiber: 0,
    sodium: 7850,
    sugar: 3.6,
  }, usda(174531, "Sauce, fish, ready-to-serve")),
  food("oyster-sauce", "蚝油", "condiment", "drop", "中式炒菜常用", 10, {
    calories: 51,
    protein: 1.4,
    fat: 0.2,
    carbs: 10.9,
    fiber: 0.3,
    sodium: 2730,
    sugar: 0,
  }, usda(174529, "Sauce, oyster, ready-to-serve")),
  food("hoisin-sauce", "海鲜酱", "condiment", "drop", "甜咸酱料，注意糖和钠", 15, {
    calories: 220,
    protein: 3.3,
    fat: 3.4,
    carbs: 44.1,
    fiber: 2.8,
    sodium: 1620,
    sugar: 27.3,
  }, usda(172886, "Sauce, hoisin, ready-to-serve")),
  food("plum-sauce", "酸梅酱", "condiment", "drop", "甜味蘸酱，注意糖", 15, {
    calories: 184,
    protein: 0.9,
    fat: 1,
    carbs: 42.8,
    fiber: 0.7,
    sodium: 538,
    sugar: 0,
  }, usda(172879, "Sauce, plum, ready-to-serve")),
  food("curry-powder", "咖喱粉", "condiment", "drop", "粉状调味，少量使用", 5, {
    calories: 325,
    protein: 14.3,
    fat: 14,
    carbs: 55.8,
    fiber: 53.2,
    sodium: 52,
    sugar: 2.8,
  }, usda(170924, "Spices, curry powder")),
  food("garlic-powder", "蒜粉", "condiment", "drop", "粉状调味，少量使用", 3, {
    calories: 331,
    protein: 16.6,
    fat: 0.7,
    carbs: 72.7,
    fiber: 9,
    sodium: 60,
    sugar: 2.4,
  }, usda(171325, "Spices, garlic powder")),
];
